version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: erp-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - erp-network
    environment:
      - VITE_API_URL=http://10.100.37.172:5000/api
    command: npm run dev

networks:
  erp-network:
    driver: bridge